name: Build and Deploy Playground

on:
  push:
    branches-ignore:
      - main  # Ignora la branca main
  pull_request:
    branches-ignore:
      - main  # Ignora la branca main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Vars
        run: export

      - name: Set Vars
        run: |
          echo "buildVersion=$(echo $GITHUB_REF_NAME)_$(echo $GITHUB_SHA | head -c7)" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: |
          make build-api VERSION=$buildVersion

      - name: Run a multi-line script
        run: |
          export
