name: Build and Deploy Playground

on:
  push:
    branches-ignore:
      - main  # Ignora la branca main
  pull_request:
    branches-ignore:
      - main  # Ignora la branca main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Vars
        run: export

      - name: Set Vars
        run: |
          export PLAY_buildVersion=$(echo $GITHUB_REF_NAME)_$(echo $GITHUB_SHA | head -c7)
          export PLAY_PLAYGROUND_ENV=play-${GITHUB_REF_NAME:0:25}
          export | grep '^declare -x PLAY_' | sed 's/declare -x PLAY_//g' >> "$GITHUB_ENV"

      #          echo "PLAYGROUND_ENV=play-$(CI_COMMIT_REF_SLUG:0:25}


#  BRANCH_DATABASE=`echo "$PLAYGROUND_ENV" | tr - _`
#  POSTGRES_URI=$PLAYGROUND_PG/$BRANCH_DATABASE
#  REDIS_URI=$DEV_REDIS/${CI_COMMIT_REF_SLUG%%-*}
#  BRANCH_HOSTNAME=$PLAYGROUND_ENV.p.mycircutor.com
#  DYNAMIC_ENVIRONMENT_URL=https://$BRANCH_HOSTNAME

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


      - name: Build the Docker image
        run: |
          make build-api VERSION=$buildVersion

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push the Docker image
        run: make push-api VERSION=$buildVersion

      - name: Run a multi-line script
        run: |
          export
