name: Build and Deploy Playground

on:
  push:
    branches-ignore:
      - main  # Ignora la branca main
  pull_request:
    branches-ignore:
      - main  # Ignora la branca main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Vars
        run: export

      - name: Set Vars
        run: |
          buildVersion=$(echo $GITHUB_REF_NAME)_$(echo $GITHUB_SHA | head -c7)
          echo "buildVersion=$buildVersion" >> "$GITHUB_ENV"
          PLAYGROUND_ENV=play-$(echo $GITHUB_REF_NAME):0:25
          echo $PLAYGROUND_ENV
#          echo "PLAYGROUND_ENV=play-$(CI_COMMIT_REF_SLUG:0:25}


#  BRANCH_DATABASE=`echo "$PLAYGROUND_ENV" | tr - _`
#  POSTGRES_URI=$PLAYGROUND_PG/$BRANCH_DATABASE
#  REDIS_URI=$DEV_REDIS/${CI_COMMIT_REF_SLUG%%-*}
#  BRANCH_HOSTNAME=$PLAYGROUND_ENV.p.mycircutor.com
#  DYNAMIC_ENVIRONMENT_URL=https://$BRANCH_HOSTNAME


      - name: Build the Docker image
        run: |
          make build-api VERSION=$buildVersion
          make push-api VERSION=$buildVersion

      - name: Run a multi-line script
        run: |
          export
