name: Build and Deploy Playground

on:
  push:
    branches-ignore:
      - main  # Ignora la branca main
  pull_request:
    branches-ignore:
      - main  # Ignora la branca main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/set-build-version
      - name: Get Vars
        run: export

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          make build-api VERSION=$buildVersion

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push the Docker image
        run: make push-api VERSION=$buildVersion

      - name: Run a multi-line script
        run: |
          export
  prepare-database:
    name: Prepare Database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/set-build-version
      - uses: ./.github/actions/set-play-variables
      - name: Set secret URIS
        run: |
          export PLAY_POSTGRES_URI=${{ secrets.DEV_POSTGRES }}/$PLAY_DATABASE
          echo "PLAY_POSTGRES_URI=$PLAY_POSTGRES_URI" >> "$GITHUB_ENV"
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends postgresql-client
      - name: Prepare Database
        run: |
          echo "SELECT 'CREATE DATABASE $PLAY_DATABASE' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$PLAY_DATABASE')\gexec" | psql $DEV_POSTGRES

  deploy:
    name: Deploy Playground
    runs-on: ubuntu-latest
    needs: [build, prepare-database]
    steps:
      - uses: actions/checkout@v2
      - name: Set secret URIS
        run: |
          export PLAY_POSTGRES_URI=${{ secrets.DEV_POSTGRES }}/$PLAY_DATABASE
          echo "PLAY_POSTGRES_URI=$PLAY_POSTGRES_URI" >> "$GITHUB_ENV"
      - name: Deploy Playground
        run: |
          echo "Deploying $buildVersion to $PLAY_HOSTNAME using DATABASE $DEV_POSTGRES/$PLAY_DATABASE"