name: Build and Deploy Playground

on:
  push:
    branches-ignore:
      - main  # Ignora la branca main
  pull_request:
    branches-ignore:
      - main  # Ignora la branca main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Set Vars
        run: |
          PLAY_buildVersion=$(echo $GITHUB_REF_NAME)_$(echo $GITHUB_SHA | head -c7)
          echo "PLAY_buildVersion=$PLAY_buildVersion" >> "$GITHUB_ENV"
          PLAY_ENV=play-${GITHUB_REF_NAME:0:25}
          echo "PLAY_ENV=$PLAY_ENV" >> "$GITHUB_ENV"
          PLAY_ENV=`echo "PLAY_ENV" | tr - _`
          echo "PLAY_DATABASE=$PLAY_DATABASE" >> "$GITHUB_ENV"
          export PLAY_HOSTNAME=$PLAY_ENV.pe.maulabs.cat
          echo "PLAY_HOSTNAME=$PLAY_HOSTNAME" >> "$GITHUB_ENV"
          export PLAY_POSTGRES_URI=${{ secrets.DEV_POSTGRES }}/$PLAY_DATABASE
          echo "PLAY_POSTGRES_URI=$PLAY_POSTGRES_URI" >> "$GITHUB_ENV"
          export PLAY_REDIS_URI=${{ secrets.DEV_REDIS }}/${GITHUB_REF_NAME%%-*}
          echo "PLAY_REDIS_URI=$PLAY_REDIS_URI" >> "$GITHUB_ENV"
          DYNAMIC_ENVIRONMENT_URL=https://$BRANCH_HOSTNAME
      - name: Get Vars
        run: export

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          make build-api VERSION=$PLAY_buildVersion

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push the Docker image
        run: make push-api VERSION=$PLAY_buildVersion

      - name: Run a multi-line script
        run: |
          export
